### ISSUE TITLE
Not working in current home assistant

### ISSUE THREAD

**Issue by sgvj** [balloob/home-assistant-android-tasker#1]
Is this still the best way to control from android/tasker?

**Comment by balloob** [comment]
No, this is pretty outdated. We don't have an active guide afaik

**Comment by sgvj** [comment]
Do you have any suggestions of what to use?
I'm guessing that 
https://play.google.com/store/apps/details?id=net.nosybore.mqttpublishplugin
Or
http://joaoapps.com/join/
Might be better control techniques?

**Comment by balloob** [comment]
Tasker will still work and a lot of people use it. Best to ask on the forums.
